/* ============================================================
 * nexus-utils.js —— GENERATED by build_all.py, 请勿手改
 * 事实源: js/utils/nexus-utils-{core,format,dom,interact,auth,notify}.js
 * 产物 = 六模块按加载顺序的确定性拼接; 直引本文件的消费方拿全量 NexusUtils
 * ============================================================ */
/* ===== utils/nexus-utils-core.js ===== */
/* nexus-utils core —— nexus-utils.js 聚合入口的本体模块（由 build_all.py 拼接），直引入口或随 nexus-all 加载 */
(function() {
    const utils = window.NexusUtils = window.NexusUtils || {};
    Object.assign(utils, {
        debounce(func, wait) {
            let timeout;
            return function(...args) {
                clearTimeout(timeout);
                timeout = setTimeout(() => func.apply(this, args), wait);
            };
        },

        throttle(func, limit) {
            let inThrottle;
            return function(...args) {
                if (!inThrottle) {
                    func.apply(this, args);
                    inThrottle = true;
                    setTimeout(() => inThrottle = false, limit);
                }
            };
        },

        generateId() {
            if (typeof crypto !== 'undefined' && typeof crypto.randomUUID === 'function') {
                return crypto.randomUUID();
            }
            return Date.now().toString(36) + Math.random().toString(36).substring(2) + Math.random().toString(36).substring(2);
        },

        deepClone(obj) {
            if (typeof structuredClone === 'function') {
                try { return structuredClone(obj); } catch (e) { }
            }
            return JSON.parse(JSON.stringify(obj));
        },

        pick(obj, keys) {
            const result = {};
            keys.forEach(key => { if (key in obj) result[key] = obj[key]; });
            return result;
        },

        omit(obj, keys) {
            const result = { ...obj };
            keys.forEach(key => delete result[key]);
            return result;
        },
    });
})();

/* ===== utils/nexus-utils-format.js ===== */
/* nexus-utils format —— nexus-utils.js 聚合入口的本体模块（由 build_all.py 拼接），直引入口或随 nexus-all 加载 */
(function() {
    const CN_TZ = 'Asia/Shanghai';
    const utils = window.NexusUtils = window.NexusUtils || {};
    Object.assign(utils, {
        parseDate(value) {
            if (!value) return null;
            if (value instanceof Date) return isNaN(value.getTime()) ? null : value;
            if (typeof value === 'number') return new Date(value);
            const s = String(value).trim();
            if (/^\d{4}-\d{2}-\d{2}$/.test(s)) {
                const d = new Date(s + 'T00:00:00+08:00');
                return isNaN(d.getTime()) ? null : d;
            }
            let str = s.replace(' ', 'T');
            if (!/(?:Z|[+-]\d{2}:?\d{2})$/i.test(str)) str += '+08:00';
            const d = new Date(str);
            return isNaN(d.getTime()) ? null : d;
        },

        formatDate(dateString, options = {}) {
            const date = utils.parseDate(dateString);
            if (!date) return '';
            try {
                return date.toLocaleString('zh-CN', {
                    year: 'numeric', month: '2-digit', day: '2-digit',
                    hour: '2-digit', minute: '2-digit',
                    timeZone: CN_TZ,
                    ...options
                });
            } catch (e) { return ''; }
        },

        formatDateShort(dateString) {
            return utils.formatDate(dateString, { hour: undefined, minute: undefined });
        },

        formatCurrency(amount) {
            if (amount === undefined || amount === null || isNaN(amount)) return '¥0';
            return '¥' + Number(amount).toLocaleString('zh-CN', { minimumFractionDigits: 0, maximumFractionDigits: 2 });
        },

        formatNumber(num, decimals = 2) {
            if (num === undefined || num === null || isNaN(num)) return '0';
            return Number(num).toLocaleString('zh-CN', { minimumFractionDigits: decimals, maximumFractionDigits: decimals });
        },

        smartNumber(num) {
            if (num === undefined || num === null || isNaN(Number(num))) return '0';
            const n = Number(num);
            if (!isFinite(n)) return String(n);
            if (Number.isInteger(n)) return String(n);
            return String(Number(n.toFixed(2)));
        },

        formatBytes(bytes) {
            if (!bytes) return '0 B';
            const units = ['B', 'KB', 'MB', 'GB', 'TB'];
            let i = Math.floor(Math.log(bytes) / Math.log(1024));
            if (i >= units.length) i = units.length - 1;
            return (bytes / Math.pow(1024, i)).toFixed(i === 0 ? 0 : 1) + ' ' + units[i];
        },

        truncateText(text, maxLength = 100) {
            if (!text) return '';
            if (text.length <= maxLength) return text;
            return text.substring(0, maxLength) + '...';
        },

        getGreeting() {
            const hour = utils.getLocalHour();
            if (hour < 6) return '夜深了';
            if (hour < 9) return '早上好';
            if (hour < 12) return '上午好';
            if (hour < 14) return '中午好';
            if (hour < 18) return '下午好';
            return '晚上好';
        },

        getLocalHour() {
            const now = new Date();
            try {
                const parts = new Intl.DateTimeFormat('zh-CN', {
                    hour: 'numeric',
                    hourCycle: 'h23',
                    timeZone: CN_TZ
                }).formatToParts(now);
                for (const p of parts) {
                    if (p.type === 'hour') {
                        const hour = parseInt(p.value, 10);
                        if (!isNaN(hour) && hour >= 0 && hour <= 23) return hour;
                    }
                }
            } catch (e) { /* fallthrough */ }
            return now.getHours();
        },

        cnTodayStr() {
            const now = new Date();
            try {
                const parts = new Intl.DateTimeFormat('zh-CN', {
                    year: 'numeric', month: '2-digit', day: '2-digit',
                    timeZone: CN_TZ
                }).formatToParts(now);
                let y = '', m = '', d = '';
                for (const p of parts) {
                    if (p.type === 'year') y = p.value;
                    else if (p.type === 'month') m = p.value;
                    else if (p.type === 'day') d = p.value;
                }
                if (y && m && d) return `${y}-${m}-${d}`;
            } catch (e) { /* fallthrough */ }
            return utils.formatDateShort(now).replace(/\//g, '-');
        },

        cnDateLabel() {
            const now = new Date();
            try {
                const parts = new Intl.DateTimeFormat('zh-CN', {
                    month: 'numeric', day: 'numeric', weekday: 'short',
                    timeZone: CN_TZ
                }).formatToParts(now);
                let m = '', d = '', w = '';
                for (const p of parts) {
                    if (p.type === 'month') m = p.value;
                    else if (p.type === 'day') d = p.value;
                    else if (p.type === 'weekday') w = p.value;
                }
                if (m && d && w) return `${m}月${d}日 ${w}`;
            } catch (e) { /* fallthrough */ }
            const today = new Date();
            const weekdays = ['周日', '周一', '周二', '周三', '周四', '周五', '周六'];
            return `${today.getMonth() + 1}月${today.getDate()}日 ${weekdays[today.getDay()]}`;
        },

        formatPhone(phone) {
            if (!phone || phone.length < 7) return phone || '';
            return phone.substring(0, 3) + '****' + phone.substring(phone.length - 4);
        },

        formatMsg(content) {
            if (!content) return '';
            let html = String(content)
                .replace(/&/g, '&amp;')
                .replace(/</g, '&lt;')
                .replace(/>/g, '&gt;')
                .replace(/"/g, '&quot;')
                .replace(/'/g, '&#39;');
            const codeBlocks = [];
            html = html.replace(/```([\s\S]*?)```/g, (m, code) => {
                codeBlocks.push(code.replace(/^\n/, ''));
                return `\x00CODEBLOCK${codeBlocks.length - 1}\x00`;
            });
            html = html.replace(/`([^`]+)`/g, (m, code) => `<code>${code}</code>`);
            html = html.replace(/\n/g, '<br>');
            codeBlocks.forEach((code, i) => {
                html = html.replace(`\x00CODEBLOCK${i}\x00`, `<pre><code>${code}</code></pre>`);
            });
            return html;
        },

        matchGrade(value, rules, mode = 'eq') {
            if (value === undefined || value === null) return null;
            const v = String(value).toLowerCase();
            for (const rule of rules) {
                const keys = Array.isArray(rule.match) ? rule.match : [rule.match];
                const hit = mode === 'has'
                    ? keys.some(k => k && v.indexOf(String(k).toLowerCase()) >= 0)
                    : keys.some(k => k !== undefined && k !== null && String(k).toLowerCase() === v);
                if (hit) return rule;
            }
            return null;
        },

        formatRelativeTime(dateString, options = {}) {
            const date = utils.parseDate(dateString);
            if (!date) return '';
            const dayLimit = options.dayLimit > 0 ? options.dayLimit : 30;
            const space = options.space === true ? ' ' : '';
            const now = Date.now();
            const diff = now - date.getTime();
            const seconds = Math.floor(diff / 1000);
            const minutes = Math.floor(seconds / 60);
            const hours = Math.floor(minutes / 60);
            const days = Math.floor(hours / 24);
            if (seconds < 60) return '刚刚';
            if (minutes < 60) return `${minutes}${space}分钟前`;
            if (hours < 24) return `${hours}${space}小时前`;
            if (days < dayLimit) return `${days}${space}天前`;
            if (options.fallback === 'md') {
                const cn = utils.cnParts(date);
                const nowCn = utils.cnParts(new Date());
                return cn.year === nowCn.year
                    ? `${cn.month}-${cn.day}`
                    : `${cn.year}-${cn.month}-${cn.day}`;
            }
            return utils.formatDateShort(dateString);
        },

        pad2(n) {
            return String(n == null ? 0 : n).padStart(2, '0');
        },

        cnParts(value) {
            const out = { year: '', month: '', day: '', hour: '', minute: '', second: '' };
            const d = value instanceof Date ? value : utils.parseDate(value);
            if (!d || isNaN(d.getTime())) return out;
            try {
                new Intl.DateTimeFormat('zh-CN', {
                    year: 'numeric', month: '2-digit', day: '2-digit',
                    hour: '2-digit', minute: '2-digit', second: '2-digit',
                    hourCycle: 'h23', timeZone: CN_TZ
                }).formatToParts(d).forEach((part) => {
                    if (Object.prototype.hasOwnProperty.call(out, part.type)) out[part.type] = part.value;
                });
            } catch (e) {}
            return out;
        },

        formatDateKey(value) {
            const d = value instanceof Date ? value : utils.parseDate(value);
            if (!d || isNaN(d.getTime())) return '';
            return d.getFullYear() + '-' + utils.pad2(d.getMonth() + 1) + '-' + utils.pad2(d.getDate());
        },

        formatDateTimeHyphen(value, withSeconds = false) {
            const d = value instanceof Date ? value : utils.parseDate(value);
            if (!d || isNaN(d.getTime())) return '';
            const p = utils.cnParts(d);
            const base = p.year + '-' + p.month + '-' + p.day + ' ' + p.hour + ':' + p.minute;
            return withSeconds ? base + ':' + p.second : base;
        },

        formatDateTime(dateString, options = {}) {
            const date = utils.parseDate(dateString);
            if (!date) return '';
            try {
                return date.toLocaleString('zh-CN', {
                    year: 'numeric', month: '2-digit', day: '2-digit',
                    hour: '2-digit', minute: '2-digit', second: '2-digit',
                    timeZone: CN_TZ,
                    ...options
                });
            } catch (e) { return ''; }
        },

        formatPercent(value, decimals = 1) {
            if (value === undefined || value === null || isNaN(value)) return '0%';
            return (Number(value) * 100).toFixed(decimals) + '%';
        },

        formatUsd(amount, decimals = 4) {
            if (amount === undefined || amount === null || isNaN(amount)) return Number(0).toFixed(decimals);
            return Number(amount).toFixed(decimals);
        },

        formatChatTime(timeStr) {
            if (!timeStr) return '';
            const date = new Date(timeStr);
            if (isNaN(date.getTime())) return '';
            const now = new Date();
            const isToday = date.getFullYear() === now.getFullYear()
                && date.getMonth() === now.getMonth()
                && date.getDate() === now.getDate();
            const hh = String(date.getHours()).padStart(2, '0');
            const mm = String(date.getMinutes()).padStart(2, '0');
            if (isToday) return `${hh}:${mm}`;
            const M = String(date.getMonth() + 1).padStart(2, '0');
            const D = String(date.getDate()).padStart(2, '0');
            return `${M}/${D} ${hh}:${mm}`;
        },

        formatTime(dateString) {
            return utils.formatRelativeTime(dateString);
        },
    });
})();

/* ===== utils/nexus-utils-dom.js ===== */
/* nexus-utils dom —— nexus-utils.js 聚合入口的本体模块（由 build_all.py 拼接），直引入口或随 nexus-all 加载 */
(function() {
    const utils = window.NexusUtils = window.NexusUtils || {};
    Object.assign(utils, {
        scrollLock: (function() {
            let count = 0;
            let prevOverflow = '';
            let prevPaddingRight = '';
            return {
                lock() {
                    count++;
                    if (count > 1) return;
                    const body = document.body;
                    prevOverflow = body.style.overflow;
                    prevPaddingRight = body.style.paddingRight;
                    const gap = window.innerWidth - document.documentElement.clientWidth;
                    body.style.overflow = 'hidden';
                    if (gap > 0) body.style.paddingRight = gap + 'px';
                },
                unlock() {
                    if (count === 0) return;
                    count--;
                    if (count > 0) return;
                    document.body.style.overflow = prevOverflow;
                    document.body.style.paddingRight = prevPaddingRight;
                }
            };
        })(),

        downloadFile(content, filename, mimeType = 'text/plain') {
            const blob = new Blob([content], { type: mimeType });
            const url = URL.createObjectURL(blob);
            const a = document.createElement('a');
            a.href = url;
            a.download = filename;
            document.body.appendChild(a);
            a.click();
            a.remove();
            URL.revokeObjectURL(url);
        },

        autoResize(el) {
            if (!el) return;
            el.style.height = 'auto';
            el.style.height = el.scrollHeight + 'px';
        },

        setViewportHeight() {
            const vh = window.innerHeight * 0.01;
            document.documentElement.style.setProperty('--nx-vh', `${vh}px`);
            document.documentElement.style.setProperty('--nx-vh-full', `${vh * 100}px`);
        },

        syncKeyboardHeight() {
            const vv = window.visualViewport;
            const kb = vv ? Math.max(0, Math.round(window.innerHeight - vv.height)) : 0;
            document.documentElement.style.setProperty('--nx-kb', `${kb}px`);
            document.documentElement.toggleAttribute('data-kb-open', kb > 0);
        },

        escapeHtml(text) {
            if (text === null || text === undefined) return '';
            return String(text)
                .replace(/&/g, '&amp;')
                .replace(/</g, '&lt;')
                .replace(/>/g, '&gt;')
                .replace(/"/g, '&quot;')
                .replace(/'/g, '&#39;');
        },

        hexToRgba(hex, alpha = 1) {
            if (typeof hex !== 'string') return `rgba(99, 102, 241, ${alpha})`;
            let h = hex.trim().replace('#', '');
            if (h.length === 3) h = h.split('').map(c => c + c).join('');
            if (!/^[0-9a-fA-F]{6}$/.test(h)) return `rgba(99, 102, 241, ${alpha})`;
            const r = parseInt(h.slice(0, 2), 16);
            const g = parseInt(h.slice(2, 4), 16);
            const b = parseInt(h.slice(4, 6), 16);
            return `rgba(${r}, ${g}, ${b}, ${alpha})`;
        },

        isDarkColor(hex) {
            if (typeof hex !== 'string' || hex.length < 7) return false;
            const h = hex.trim().replace('#', '');
            if (!/^[0-9a-fA-F]{6}$/.test(h)) return false;
            const r = parseInt(h.slice(0, 2), 16);
            const g = parseInt(h.slice(2, 4), 16);
            const b = parseInt(h.slice(4, 6), 16);
            return (0.299 * r + 0.587 * g + 0.114 * b) / 255 < 0.5;
        },

        compressImage(file, opts = {}) {
            const maxDim = opts.maxDim || 1600;
            const quality = opts.quality || 0.85;
            const output = opts.output || 'file';
            return new Promise((resolve) => {
                if (!file || !/^image\//.test(file.type || '')) { resolve(file); return; }
                const url = URL.createObjectURL(file);
                const img = new Image();
                img.onerror = () => { URL.revokeObjectURL(url); resolve(file); };
                img.onload = () => {
                    URL.revokeObjectURL(url);
                    const longest = Math.max(img.width || 1, img.height || 1);
                    const mime = opts.mime || (file.type === 'image/png' ? 'image/png' : 'image/jpeg');
                    if (longest <= maxDim && mime === file.type && output === 'file') { resolve(file); return; }
                    const scale = Math.min(1, maxDim / longest);
                    const canvas = document.createElement('canvas');
                    canvas.width = Math.max(1, Math.round((img.width || 1) * scale));
                    canvas.height = Math.max(1, Math.round((img.height || 1) * scale));
                    const ctx = canvas.getContext('2d');
                    if (mime === 'image/jpeg') { ctx.fillStyle = '#ffffff'; ctx.fillRect(0, 0, canvas.width, canvas.height); }
                    ctx.drawImage(img, 0, 0, canvas.width, canvas.height);
                    if (output === 'dataurl') { resolve(canvas.toDataURL(mime, quality)); return; }
                    canvas.toBlob((blob) => {
                        if (!blob) { resolve(file); return; }
                        if (output === 'blob') { resolve(blob); return; }
                        const base = (file.name || 'image').replace(/\.[^.\/]+$/, '');
                        const ext = mime === 'image/png' ? '.png' : '.jpg';
                        resolve(new File([blob], base + ext, { type: mime }));
                    }, mime, quality);
                };
                img.src = url;
            });
        },

        isDarkTheme() {
            return document.documentElement.getAttribute('data-theme') === 'dark';
        },

        chartText(darkColor = '#a0a0a0', lightColor = '#333') {
            return utils.isDarkTheme() ? darkColor : lightColor;
        },

        getPathPrefix() {
            if (window.PATH_PREFIX) return window.PATH_PREFIX;
            const scripts = document.querySelectorAll('script[src]');
            for (const script of scripts) {
                const src = script.getAttribute('src');
                if (src && src.startsWith('/') && !src.startsWith('//')) {
                    const match = src.match(/^\/([^/]+)\//);
                    if (match && match[1] !== 'static' && match[1] !== 'api') {
                        window.PATH_PREFIX = '/' + match[1];
                        return window.PATH_PREFIX;
                    }
                }
            }
            window.PATH_PREFIX = '';
            return '';
        },

        prefersReducedMotion() {
            try {
                return !!(window.matchMedia && window.matchMedia('(prefers-reduced-motion: reduce)').matches);
            } catch (e) { return false; }
        },

        injectStyle(id, css) {
            if (!id || document.getElementById(id)) return;
            const style = document.createElement('style');
            style.id = id;
            style.textContent = Array.isArray(css) ? css.join('\n') : css;
            (document.head || document.documentElement).appendChild(style);
        },

        motionDuration(ms) {
            return utils.prefersReducedMotion() ? 0 : ms;
        },
    });
    utils.setViewportHeight();
    utils._resizeHandler = utils.debounce(utils.setViewportHeight, 100);
    window.addEventListener('resize', utils._resizeHandler);
    if (window.visualViewport) {
        utils.syncKeyboardHeight();
        window.visualViewport.addEventListener('resize', utils.syncKeyboardHeight);
    }
})();

/* ===== utils/nexus-utils-interact.js ===== */
/* nexus-utils interact —— nexus-utils.js 聚合入口的本体模块（由 build_all.py 拼接），直引入口或随 nexus-all 加载 */
(function() {
    const utils = window.NexusUtils = window.NexusUtils || {};
    Object.assign(utils, {
        copyToClipboard(text) {
            if (navigator.clipboard && navigator.clipboard.writeText) {
                return navigator.clipboard.writeText(text).then(() => true).catch(() => utils._copyFallback(text));
            }
            return Promise.resolve(utils._copyFallback(text));
        },

        _copyFallback(text) {
            const textarea = document.createElement('textarea');
            textarea.value = text;
            textarea.style.position = 'fixed';
            textarea.style.opacity = '0';
            document.body.appendChild(textarea);
            textarea.select();
            let ok = false;
            try { ok = document.execCommand('copy'); } catch (e) { ok = false; }
            textarea.remove();
            return ok;
        },

        copyText(text, opts = {}) {
            return utils.copyToClipboard(text).then((ok) => {
                if (ok) {
                    if (opts.success) utils.showToast(opts.success, opts.type || 'success');
                } else if (opts.fail) {
                    utils.showToast(opts.fail, 'error');
                }
                return ok;
            });
        },

        showToast(message, type = 'info', options = {}) {
            if (typeof window.showToast !== 'function') return;
            const opts = options || {};
            if (opts.center) {
                window.showToast(message, type, { duration: opts.duration || 3000, center: true });
            } else {
                window.showToast(message, type, opts.duration || 3000);
            }
        },

        confirm(message, title = '操作确认', options = {}) {
            if (typeof window.nuxConfirm !== 'function') return Promise.resolve(false);
            return window.nuxConfirm(message, title, options);
        },
    });
    utils.errorDetailText = function (v) {
        if (v === null || v === undefined) return '';
        if (typeof v === 'string') return v.trim();
        if (Array.isArray(v)) {
            return v.map(function (item) {
                if (item === null || item === undefined) return '';
                if (typeof item === 'string') return item;
                if (typeof item === 'object') {
                    return String(item.msg || item.message || item.detail || '').replace(/^Value error,\s*/, '');
                }
                return String(item);
            }).filter(Boolean).join('；');
        }
        if (typeof v === 'object') {
            var inner = v.message || v.detail || v.msg || v.error;
            if (inner === undefined || inner === v) return '';
            return utils.errorDetailText(inner);
        }
        return String(v);
    };

    utils.FOCUSABLE_SELECTOR = 'a[href], button:not([disabled]), textarea:not([disabled]), input:not([disabled]), select:not([disabled]), [tabindex]:not([tabindex="-1"])';
    utils.focusables = function (root) {
        if (!root) return [];
        return Array.prototype.slice.call(root.querySelectorAll(utils.FOCUSABLE_SELECTOR)).filter(function (el) {
            return el.offsetParent !== null;
        });
    };

    // 方向键在列表索引间移动（左右/上下/Home/End，首尾环绕）；非导航键返回 -1
    utils.rovingIndex = function (e, count, current) {
        if (!count || count <= 0) return -1;
        let idx = (current === undefined || current < 0 || current >= count) ? 0 : current;
        switch (e.key) {
            case 'ArrowRight': case 'ArrowDown': idx += 1; break;
            case 'ArrowLeft': case 'ArrowUp': idx -= 1; break;
            case 'Home': idx = 0; break;
            case 'End': idx = count - 1; break;
            default: return -1;
        }
        if (idx < 0) idx = count - 1;
        if (idx >= count) idx = 0;
        return idx;
    };

    utils.overlayStack = function () {
        const stack = [];
        return {
            push(uid) { stack.push(uid); },
            remove(uid) { const i = stack.indexOf(uid); if (i > -1) stack.splice(i, 1); },
            isTop(uid) { return stack[stack.length - 1] === uid; }
        };
    };

    utils.overlayBehavior = function (options) {
        const opts = options || {};
        const canInteract = opts.canInteract || (() => true);
        const escEnabled = opts.escEnabled || (() => true);
        let restoreEl = null;
        let active = false;

        function trapTab(e) {
            const panel = opts.panel ? opts.panel() : null;
            if (!panel) return;
            const list = utils.focusables(panel);
            if (!list.length) return;
            const first = list[0];
            const last = list[list.length - 1];
            if (e.shiftKey && document.activeElement === first) {
                e.preventDefault();
                last.focus();
            } else if (!e.shiftKey && document.activeElement === last) {
                e.preventDefault();
                first.focus();
            }
        }

        function onKeydown(e) {
            if (!canInteract()) return;
            if (e.key === 'Escape') {
                if (escEnabled()) opts.requestClose();
                return;
            }
            if (e.key === 'Tab' && opts.trap !== false) trapTab(e);
        }

        function focusPanel() {
            let el = opts.focusEl ? opts.focusEl() : null;
            if (!el && opts.panel) {
                const list = utils.focusables(opts.panel());
                el = list.length ? list[0] : null;
            }
            if (el && el.focus) {
                try { el.focus(); } catch (e) { }
            }
        }

        function acquire() {
            if (active) return;
            active = true;
            if (opts.stack) opts.stack.push(opts.uid);
            if (utils.scrollLock) utils.scrollLock.lock();
            if (document.activeElement && document.activeElement !== document.body) {
                restoreEl = document.activeElement;
            }
            document.addEventListener('keydown', onKeydown);
            const schedule = (window.Vue && Vue.nextTick) ? Vue.nextTick
                : (window.requestAnimationFrame ? window.requestAnimationFrame : function (fn) { fn(); });
            schedule(focusPanel);
        }

        function release() {
            if (!active) return;
            active = false;
            document.removeEventListener('keydown', onKeydown);
            if (opts.stack) opts.stack.remove(opts.uid);
            if (utils.scrollLock) utils.scrollLock.unlock();
            if (restoreEl && restoreEl.focus) {
                try { restoreEl.focus(); } catch (e) { }
            }
            restoreEl = null;
        }

        return { acquire, release };
    };
})();

/* ===== utils/nexus-utils-auth.js ===== */
/* nexus-utils auth —— nexus-utils.js 聚合入口的本体模块（由 build_all.py 拼接），直引入口或随 nexus-all 加载 */
(function() {
    const SSO_COOKIE_DOMAIN = '.songguokr.com';
    const SSO_LOGOUT_COOKIE = 'uc_sso_logout';
    const SSO_LOGOUT_MAX_AGE = 30 * 24 * 3600;
    const SSO_EPOCH_KEY = 'uc_session_epoch';
    const utils = window.NexusUtils = window.NexusUtils || {};
    Object.assign(utils, {
        ssoCookieDomain() {
            try {
                const host = window.location.hostname || '';
                if (host === 'localhost' || host === '127.0.0.1') return null;
                return (host === 'songguokr.com' || host.endsWith('.songguokr.com')) ? SSO_COOKIE_DOMAIN : null;
            } catch (e) { return null; }
        },

        markSsoLogout() {
            try { window.localStorage.removeItem(SSO_EPOCH_KEY); } catch (e) {}
            if (!utils.ssoCookieDomain()) return;
            try {
                document.cookie = SSO_LOGOUT_COOKIE + '=' + Date.now() +
                    ';Domain=' + SSO_COOKIE_DOMAIN + ';Path=/;Max-Age=' + SSO_LOGOUT_MAX_AGE + ';SameSite=Lax';
            } catch (e) {}
        },

        ssoLogoutPending() {
            if (!utils.ssoCookieDomain()) return false;
            try {
                const epoch = window.localStorage.getItem(SSO_EPOCH_KEY);
                if (!epoch) return false;
                const m = document.cookie.match(new RegExp('(?:^|;\\s*)' + SSO_LOGOUT_COOKIE + '=(\\d+)'));
                if (!m) return false;
                return parseInt(m[1], 10) > parseInt(epoch, 10);
            } catch (e) { return false; }
        },

        ssoSessionGuard() {
            if (!utils.ssoLogoutPending()) return false;
            utils.clearAuthState();
            return true;
        },

        createDualStorage(tokenKey = 'uc_access_token') {
            const read = (s, k) => { try { return s.getItem(k); } catch (e) { return null; } };
            const write = (s, k, v) => { try { s.setItem(k, v); } catch (e) {} };
            const clear = (s, k) => { try { s.removeItem(k); } catch (e) {} };
            const preferSession = () => read(window.sessionStorage, tokenKey) !== null;
            const SSO_COOKIE = 'uc_sso_token';
            const BRIDGE_KEYS = ['uc_access_token', 'uc_refresh_token', 'uc_token_expires_at'];
            const ssoDomain = () => utils.ssoCookieDomain();
            const readStorage = (key) => {
                const v = read(window.sessionStorage, key);
                if (v !== null) return v;
                return read(window.localStorage, key);
            };
            const readBridge = () => {
                const domain = ssoDomain();
                if (!domain) return null;
                try {
                    const m = document.cookie.match(new RegExp('(?:^|;\\s*)' + SSO_COOKIE + '=([^;]+)'));
                    if (!m) return null;
                    const data = JSON.parse(decodeURIComponent(m[1]));
                    return data && data.a ? data : null;
                } catch (e) { return null; }
            };
            const bridgeValue = (key) => {
                const data = readBridge();
                if (!data) return null;
                if (key === 'uc_access_token') return data.a;
                if (key === 'uc_refresh_token') return data.r;
                if (key === 'uc_token_expires_at') return data.e !== undefined && data.e !== null ? String(data.e) : null;
                return null;
            };
            const writeBridge = () => {
                const domain = ssoDomain();
                if (!domain) return;
                const access = readStorage('uc_access_token');
                if (!access) return;
                const refresh = readStorage('uc_refresh_token');
                const expires = readStorage('uc_token_expires_at');
                const payload = encodeURIComponent(JSON.stringify({ a: access, r: refresh, e: expires ? parseInt(expires) : null }));
                const maxAge = preferSession() ? '' : ';Max-Age=' + (30 * 24 * 3600);
                try {
                    document.cookie = SSO_COOKIE + '=' + payload + ';Domain=' + domain + ';Path=/;SameSite=Lax' + maxAge;
                } catch (e) {}
            };
            const clearBridge = () => {
                const domain = ssoDomain();
                if (!domain) return;
                try {
                    document.cookie = SSO_COOKIE + '=;Domain=' + domain + ';Path=/;Max-Age=0';
                } catch (e) {}
            };
            const resolveKey = (key) => (key === undefined || key === null ? tokenKey : key);
            return {
                getItem(key) {
                    const k = resolveKey(key);
                    const v = readStorage(k);
                    if (v !== null) return v;
                    return BRIDGE_KEYS.indexOf(k) !== -1 ? bridgeValue(k) : null;
                },
                setItem(key, value) {
                    const k = resolveKey(key);
                    const useSession = preferSession();
                    write(useSession ? window.sessionStorage : window.localStorage, k, value);
                    clear(useSession ? window.localStorage : window.sessionStorage, k);
                    if (k === tokenKey && value) {
                        try { window.localStorage.setItem(SSO_EPOCH_KEY, String(Date.now())); } catch (e) {}
                    }
                    if (BRIDGE_KEYS.indexOf(k) !== -1) writeBridge();
                },
                removeItem(key) {
                    const k = resolveKey(key);
                    clear(window.sessionStorage, k);
                    clear(window.localStorage, k);
                    if (BRIDGE_KEYS.indexOf(k) !== -1) clearBridge();
                }
            };
        },

        authToken() {
            return utils.createDualStorage('uc_access_token').getItem() || '';
        },

        clearAuthState() {
            try {
                const ds = utils.createDualStorage('uc_access_token');
                ['uc_access_token', 'uc_refresh_token', 'uc_token_expires_at'].forEach((k) => ds.removeItem(k));
            } catch (e) {}
            try { window.localStorage.removeItem(SSO_EPOCH_KEY); } catch (e) {}
            try { window.dispatchEvent(new CustomEvent('uc:authchange', { detail: { authenticated: false } })); } catch (e) {}
        },

        consumeReturnUrl() {
            try {
                const v = window.sessionStorage.getItem('nux_return_url');
                if (v) window.sessionStorage.removeItem('nux_return_url');
                return v;
            } catch (e) { return null; }
        },

        handleUnauthorized(opts = {}) {
            utils.clearAuthState();
            const msg = opts.message || '登录已过期，请重新登录';
            utils.showToast(msg, 'error');
            const redirect = opts.redirect || utils.consumeReturnUrl() || window.location.pathname + window.location.search;
            setTimeout(() => {
                const target = '/login.html?redirect=' + encodeURIComponent('/' + String(redirect).replace(/^\/+/, ''));
                window.location.href = target;
            }, opts.delay || 1200);
        }
    });
})();

/* ===== utils/nexus-utils-notify.js ===== */
/* nexus-utils notify —— nexus-utils.js 聚合入口的本体模块（由 build_all.py 拼接），直引入口或随 nexus-all 加载 */
(function() {
    const utils = window.NexusUtils = window.NexusUtils || {};
    utils.notify = (function () {
        const APP_PATHS = {
            'resumeai': '/resumeai/', 'challengeplanet': '/challengeplanet/',
            'nexus-agent': '/nexus-agent', 'travelmate': '/travelmate/',
            'onenote': '/onenote/', 'wisepath': '/wisepath/', 'gezhi': '/gezhi/',
            'goldenfish': '/goldenfish/', 'versecraft': '/versecraft/',
            'miaobi': '/miaobi/', 'geniusstudent': '/geniusstudent/',
            'aipet': '/aipet/', 'lifecompass': '/lifecompass/', 'truemirror': '/truemirror/',
            'suki': '/suki/', 'lyra': '/lyra/', 'codeblock': '/codeblock/',
            'promptgenius': '/promptgenius/', 'financialkg': '/financialkg/',
            'goldenstock': '/golden/', 'beememory': '/beememory/', 'drawio': '/drawio/'
        };
        const APP_LABELS = {
            'resumeai': '跃职', 'challengeplanet': '星轨挑战', 'onenote': '拾光',
            'wisepath': '智途志愿', 'gezhi': '格致', 'travelmate': '拾途旅行', 'miaobi': '秒笔',
            'aipet': '宠康管家', 'lifecompass': '司南', 'truemirror': '照妖镜',
            'geniusstudent': '天才学伴', 'codeblock': '编程学伴', 'suki': '璇玑',
            'lyra': '灵弦', 'nexus-agent': '灵犀', 'promptgenius': '镕裁',
            'financialkg': '知识图谱', 'goldenfish': '金鱼助手',
            'goldenstock': '金股智投', 'golden': '金股智投', 'versecraft': '墨韵创作',
            'beememory': '蜜蜂记忆', 'minideploy': '部署平台',
            'userfeedback': '意见反馈', 'usercenter': '钱包',
            'notifycenter': '通知中心', 'system': '系统'
        };
        function normalize(url) {
            if (!url || url.charAt(0) !== '/') return url;
            const seg = url.split('/')[1] || '';
            const canonical = APP_PATHS[seg.toLowerCase()];
            if (!canonical) return url;
            return canonical.replace(/\/$/, '') + url.slice(seg.length + 1);
        }
        function resolve(item) {
            if (!item) return '';
            let url = item.link || '';
            if (!url) {
                const d = item.data || {};
                if (typeof d.url === 'string' && d.url) url = d.url;
                else if (Array.isArray(d.jobs) && d.jobs.length && d.jobs[0]
                    && typeof d.jobs[0].url === 'string') url = d.jobs[0].url || '';
            }
            if (!url) url = APP_PATHS[String(item.app_id || '').toLowerCase()] || '';
            return normalize(url);
        }
        function appLabel(appId) {
            const key = String(appId || '').toLowerCase();
            return APP_LABELS[key] || (key ? key.charAt(0).toUpperCase() + key.slice(1) : '');
        }
        function isToday(iso) {
            if (!iso) return false;
            const d = new Date(iso);
            if (isNaN(d.getTime())) return false;
            const now = new Date();
            return d.getFullYear() === now.getFullYear()
                && d.getMonth() === now.getMonth() && d.getDate() === now.getDate();
        }
        function jobEntries(item) {
            const jobs = item && item.data && item.data.jobs;
            if (!Array.isArray(jobs)) return [];
            return jobs.filter(j => j && (typeof j.job_title === 'string' || typeof j.title === 'string'))
                .slice(0, 3)
                .map(j => ({
                    title: j.job_title || j.title || '',
                    company: typeof j.company === 'string' ? j.company : '',
                    url: (typeof j.url === 'string' && j.url) ? normalize(j.url) : ''
                }));
        }
        return { resolve, normalize, appLabel, isToday, jobEntries };
    })();
})();
