(function () {
    'use strict';

    const UC_PREFIX = 'uc_';
    const AUTO_PREFIX = 'user_';
    const GUEST_PREFIX = 'guest_';
    const DEFAULT_NAME = '星友';
    const PLACEHOLDER_TOKENS = { unknown: 1, 未知: 1, undefined: 1, null: 1, none: 1, 'n/a': 1, '未设置': 1, '未命名': 1, '匿名': 1 };
    const SYNTHETIC_EMAIL_MARK = '@users.internal';

    function isUcFallback(value) {
        if (typeof value !== 'string') return false;
        return value.indexOf(UC_PREFIX) === 0 || value.indexOf(AUTO_PREFIX) === 0 || value.indexOf(GUEST_PREFIX) === 0;
    }

    function isSyntheticEmail(email) {
        return typeof email === 'string' && email.trim().toLowerCase().indexOf(SYNTHETIC_EMAIL_MARK) > 0;
    }

    function isAutoGenerated(name, userId) {
        if (typeof name !== 'string') return true;
        const value = name.trim();
        if (!value) return true;
        if (/^\d+$/.test(value)) return true;
        if (PLACEHOLDER_TOKENS[value.toLowerCase()]) return true;
        if (userId && value === String(userId)) return true;
        if (value.indexOf('用户') === 0) return true;
        return isUcFallback(value);
    }

    function maskPhone(phone) {
        if (typeof phone !== 'string') return '';
        const p = phone.trim();
        if (p.length >= 7) return p.slice(0, 3) + '****' + p.slice(-4);
        return p ? '****' : '';
    }

    function maskEmail(email) {
        if (typeof email !== 'string') return '';
        const e = email.trim();
        const at = e.indexOf('@');
        if (at <= 0) return e;
        const local = e.slice(0, at);
        const domain = e.slice(at + 1);
        if (local.length <= 1) return local + '***@' + domain;
        return local[0] + '***' + local[local.length - 1] + '@' + domain;
    }

    function getDisplayName(user) {
        if (!user) return '';
        const userId = user.user_id != null ? String(user.user_id) : '';
        const candidates = ['resolved_display_name', 'display_name', 'nickname', 'username', 'full_name', 'name'];
        for (let i = 0; i < candidates.length; i++) {
            const raw = user[candidates[i]];
            if (raw === undefined || raw === null) continue;
            if (!isAutoGenerated(raw, userId)) return String(raw).trim();
        }
        const email = String(user.email || '').trim();
        if (email && !isSyntheticEmail(email)) return maskEmail(email);
        const phone = String(user.phone || '').trim();
        if (phone) return maskPhone(phone);
        return DEFAULT_NAME;
    }

    function resolveName(user, fallback) {
        const name = getDisplayName(user);
        return name || fallback || '';
    }

    const NexusUser = { getDisplayName: getDisplayName, resolveName: resolveName, isUcFallback: isUcFallback };

    if (window.NexusUtils && typeof window.NexusUtils === 'object') {
        window.NexusUtils.getDisplayName = getDisplayName;
    }

    window.NexusUser = NexusUser;
})();