#!/usr/bin/env python3
"""从 js/ 独立源文件确定性重建 nexus-all.js 聚合包, 消除手工同步导致的转义损坏与内容漂移。

用法:
    python3 nexus-ui/build_all.py
"""
import os
import sys

ROOT = os.path.dirname(os.path.abspath(__file__))
JS_DIR = os.path.join(ROOT, "js")
OUT = os.path.join(JS_DIR, "nexus-all.js")

FILES: list[str] = [
    "utils/nexus-utils-core.js",
    "utils/nexus-utils-format.js",
    "utils/nexus-utils-dom.js",
    "utils/nexus-utils-interact.js",
    "utils/nexus-utils-auth.js",
    "utils/nexus-utils-notify.js",
    "nexus-overlay-host.js",
    "nexus-validators.js",
    "nexus-api-error.js",
    "nexus-stream.js",
    "nexus-api.js",
    "nexus-api-factory.js",
    "nexus-markdown.js",
    "nexus-chat.js",
    "nexus-structured.js",
    "nexus-crud.js",
    "nexus-mobile.js",
    "nexus-pull-refresh.js",
    "nexus-components.js",
    "components/nux-icon-data.js",
    "user-center-sdk.js",
    "nexus-credit-float.js",
    "nexus-feedback-float.js",
    "components/nux-result-view.js",
    "core/nexus-user.js",
    "core/nexus-error-text.js",
    "components/nux-ai-badge.js",
    "components/nux-skeleton.js",
    "components/nux-empty-state.js",
    "components/nux-error-state.js",
    "components/nux-ai-indicator.js",
    "components/nux-bottom-nav.js",
    "core/nexus-app.js",
]


UTILS_PARTS: list[str] = FILES[:6]
ENTRY = os.path.join(JS_DIR, "nexus-utils.js")
ENTRY_BANNER = """/* ============================================================
 * nexus-utils.js —— GENERATED by build_all.py, 请勿手改
 * 事实源: js/utils/nexus-utils-{core,format,dom,interact,auth,notify}.js
 * 产物 = 六模块按加载顺序的确定性拼接; 直引本文件的消费方拿全量 NexusUtils
 * ============================================================ */
"""


def main() -> int:
    parts: list[str] = []
    for name in FILES:
        with open(os.path.join(JS_DIR, name), encoding="utf-8") as f:
            content: str = f.read()
        parts.append(f"/* ===== {name} ===== */\n{content.rstrip()}\n")
    output: str = "\n".join(parts)
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write(output)
    entry_parts: list[str] = []
    for name in UTILS_PARTS:
        with open(os.path.join(JS_DIR, name), encoding="utf-8") as f:
            content: str = f.read()
        entry_parts.append(f"/* ===== {name} ===== */\n{content.rstrip()}\n")
    with open(ENTRY, "w", encoding="utf-8", newline="\n") as f:
        f.write(ENTRY_BANNER + "\n".join(entry_parts))
    print(f"[build] {len(FILES)} 个文件 -> js/nexus-all.js ({len(output.encode())} bytes)")
    print(f"[build] {len(UTILS_PARTS)} 个 utils 模块 -> js/nexus-utils.js 聚合入口")
    return 0


if __name__ == "__main__":
    sys.exit(main())